// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: categories.sql

package db

import (
	"context"
)

const CountCategories = `-- name: CountCategories :one
SELECT COUNT(*) FROM categories WHERE is_active = true
`

func (q *Queries) CountCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    name, slug, source_type, source_url, is_active
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, name, slug, source_type, source_url, is_active, created_at, updated_at
`

type CreateCategoryParams struct {
	Name       string `json:"name"`
	Slug       string `json:"slug"`
	SourceType string `json:"source_type"`
	SourceUrl  string `json:"source_url"`
	IsActive   bool   `json:"is_active"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (*Category, error) {
	row := q.db.QueryRowContext(ctx, CreateCategory,
		arg.Name,
		arg.Slug,
		arg.SourceType,
		arg.SourceUrl,
		arg.IsActive,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SourceType,
		&i.SourceUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetActiveCategories = `-- name: GetActiveCategories :many
SELECT id, name, slug, source_type, source_url, is_active, created_at, updated_at FROM categories WHERE is_active = true ORDER BY name
`

func (q *Queries) GetActiveCategories(ctx context.Context) ([]*Category, error) {
	rows, err := q.db.QueryContext(ctx, GetActiveCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.SourceType,
			&i.SourceUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetCategoriesBySourceType = `-- name: GetCategoriesBySourceType :many
SELECT id, name, slug, source_type, source_url, is_active, created_at, updated_at FROM categories WHERE source_type = $1 AND is_active = true ORDER BY name
`

func (q *Queries) GetCategoriesBySourceType(ctx context.Context, sourceType string) ([]*Category, error) {
	rows, err := q.db.QueryContext(ctx, GetCategoriesBySourceType, sourceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.SourceType,
			&i.SourceUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, slug, source_type, source_url, is_active, created_at, updated_at FROM categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id int32) (*Category, error) {
	row := q.db.QueryRowContext(ctx, GetCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SourceType,
		&i.SourceUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug, source_type, source_url, is_active, created_at, updated_at FROM categories WHERE slug = $1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (*Category, error) {
	row := q.db.QueryRowContext(ctx, GetCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SourceType,
		&i.SourceUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const UpdateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2, source_url = $3, is_active = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, source_type, source_url, is_active, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	SourceUrl string `json:"source_url"`
	IsActive  bool   `json:"is_active"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (*Category, error) {
	row := q.db.QueryRowContext(ctx, UpdateCategory,
		arg.ID,
		arg.Name,
		arg.SourceUrl,
		arg.IsActive,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SourceType,
		&i.SourceUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
