// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: forum_posts.sql

package db

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const CountPostsByCategory = `-- name: CountPostsByCategory :one
SELECT COUNT(*) FROM forum_topics WHERE category_id = $1
`

func (q *Queries) CountPostsByCategory(ctx context.Context, categoryID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountPostsByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountPostsLast24h = `-- name: CountPostsLast24h :one
SELECT COUNT(*) FROM forum_topics
WHERE created_at > NOW() - INTERVAL '24 hours'
`

func (q *Queries) CountPostsLast24h(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountPostsLast24h)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountTotalPosts = `-- name: CountTotalPosts :one
SELECT COUNT(*) FROM forum_topics
`

func (q *Queries) CountTotalPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountTotalPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateForumPost = `-- name: CreateForumPost :one
INSERT INTO forum_topics (
    category_id, title, author, source_topic_id, source_url,
    content, reply_count, view_count, last_post_time,
    content_hash, has_images, image_urls, is_notified
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, false
) RETURNING id, category_id, title, author, source_topic_id, source_url, content, reply_count, view_count, last_post_time, content_hash, has_images, image_urls, is_notified, created_at, updated_at
`

type CreateForumPostParams struct {
	CategoryID    int32     `json:"category_id"`
	Title         string    `json:"title"`
	Author        string    `json:"author"`
	SourceTopicID string    `json:"source_topic_id"`
	SourceUrl     string    `json:"source_url"`
	Content       string    `json:"content"`
	ReplyCount    int32     `json:"reply_count"`
	ViewCount     int32     `json:"view_count"`
	LastPostTime  time.Time `json:"last_post_time"`
	ContentHash   string    `json:"content_hash"`
	HasImages     bool      `json:"has_images"`
	ImageUrls     []string  `json:"image_urls"`
}

func (q *Queries) CreateForumPost(ctx context.Context, arg CreateForumPostParams) (*ForumTopic, error) {
	row := q.db.QueryRowContext(ctx, CreateForumPost,
		arg.CategoryID,
		arg.Title,
		arg.Author,
		arg.SourceTopicID,
		arg.SourceUrl,
		arg.Content,
		arg.ReplyCount,
		arg.ViewCount,
		arg.LastPostTime,
		arg.ContentHash,
		arg.HasImages,
		pq.Array(arg.ImageUrls),
	)
	var i ForumTopic
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Author,
		&i.SourceTopicID,
		&i.SourceUrl,
		&i.Content,
		&i.ReplyCount,
		&i.ViewCount,
		&i.LastPostTime,
		&i.ContentHash,
		&i.HasImages,
		pq.Array(&i.ImageUrls),
		&i.IsNotified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetForumPostByContentHash = `-- name: GetForumPostByContentHash :one
SELECT id, category_id, title, author, source_topic_id, source_url, content, reply_count, view_count, last_post_time, content_hash, has_images, image_urls, is_notified, created_at, updated_at FROM forum_topics WHERE content_hash = $1
`

func (q *Queries) GetForumPostByContentHash(ctx context.Context, contentHash string) (*ForumTopic, error) {
	row := q.db.QueryRowContext(ctx, GetForumPostByContentHash, contentHash)
	var i ForumTopic
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Author,
		&i.SourceTopicID,
		&i.SourceUrl,
		&i.Content,
		&i.ReplyCount,
		&i.ViewCount,
		&i.LastPostTime,
		&i.ContentHash,
		&i.HasImages,
		pq.Array(&i.ImageUrls),
		&i.IsNotified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetForumPostBySourceID = `-- name: GetForumPostBySourceID :one
SELECT id, category_id, title, author, source_topic_id, source_url, content, reply_count, view_count, last_post_time, content_hash, has_images, image_urls, is_notified, created_at, updated_at FROM forum_topics
WHERE source_topic_id = $1 AND category_id = $2
`

type GetForumPostBySourceIDParams struct {
	SourceTopicID string `json:"source_topic_id"`
	CategoryID    int32  `json:"category_id"`
}

func (q *Queries) GetForumPostBySourceID(ctx context.Context, arg GetForumPostBySourceIDParams) (*ForumTopic, error) {
	row := q.db.QueryRowContext(ctx, GetForumPostBySourceID, arg.SourceTopicID, arg.CategoryID)
	var i ForumTopic
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Author,
		&i.SourceTopicID,
		&i.SourceUrl,
		&i.Content,
		&i.ReplyCount,
		&i.ViewCount,
		&i.LastPostTime,
		&i.ContentHash,
		&i.HasImages,
		pq.Array(&i.ImageUrls),
		&i.IsNotified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetForumPostByURL = `-- name: GetForumPostByURL :one
SELECT id, category_id, title, author, source_topic_id, source_url, content, reply_count, view_count, last_post_time, content_hash, has_images, image_urls, is_notified, created_at, updated_at FROM forum_topics WHERE source_url = $1
`

func (q *Queries) GetForumPostByURL(ctx context.Context, sourceUrl string) (*ForumTopic, error) {
	row := q.db.QueryRowContext(ctx, GetForumPostByURL, sourceUrl)
	var i ForumTopic
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Author,
		&i.SourceTopicID,
		&i.SourceUrl,
		&i.Content,
		&i.ReplyCount,
		&i.ViewCount,
		&i.LastPostTime,
		&i.ContentHash,
		&i.HasImages,
		pq.Array(&i.ImageUrls),
		&i.IsNotified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetLastScrapingTime = `-- name: GetLastScrapingTime :one
SELECT MAX(created_at) FROM forum_topics
`

func (q *Queries) GetLastScrapingTime(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, GetLastScrapingTime)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const GetPostsByCategory = `-- name: GetPostsByCategory :many
SELECT id, category_id, title, author, source_topic_id, source_url, content, reply_count, view_count, last_post_time, content_hash, has_images, image_urls, is_notified, created_at, updated_at FROM forum_topics
WHERE category_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetPostsByCategoryParams struct {
	CategoryID int32 `json:"category_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) GetPostsByCategory(ctx context.Context, arg GetPostsByCategoryParams) ([]*ForumTopic, error) {
	rows, err := q.db.QueryContext(ctx, GetPostsByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ForumTopic{}
	for rows.Next() {
		var i ForumTopic
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Title,
			&i.Author,
			&i.SourceTopicID,
			&i.SourceUrl,
			&i.Content,
			&i.ReplyCount,
			&i.ViewCount,
			&i.LastPostTime,
			&i.ContentHash,
			&i.HasImages,
			pq.Array(&i.ImageUrls),
			&i.IsNotified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRecentForumPosts = `-- name: GetRecentForumPosts :many
SELECT ft.id, ft.category_id, ft.title, ft.author, ft.source_topic_id, ft.source_url, ft.content, ft.reply_count, ft.view_count, ft.last_post_time, ft.content_hash, ft.has_images, ft.image_urls, ft.is_notified, ft.created_at, ft.updated_at, c.name as category_name
FROM forum_topics ft
JOIN categories c ON ft.category_id = c.id
WHERE ft.created_at > $1
ORDER BY ft.created_at DESC
LIMIT $2
`

type GetRecentForumPostsParams struct {
	CreatedAt time.Time `json:"created_at"`
	Limit     int32     `json:"limit"`
}

type GetRecentForumPostsRow struct {
	ID            int32     `json:"id"`
	CategoryID    int32     `json:"category_id"`
	Title         string    `json:"title"`
	Author        string    `json:"author"`
	SourceTopicID string    `json:"source_topic_id"`
	SourceUrl     string    `json:"source_url"`
	Content       string    `json:"content"`
	ReplyCount    int32     `json:"reply_count"`
	ViewCount     int32     `json:"view_count"`
	LastPostTime  time.Time `json:"last_post_time"`
	ContentHash   string    `json:"content_hash"`
	HasImages     bool      `json:"has_images"`
	ImageUrls     []string  `json:"image_urls"`
	IsNotified    bool      `json:"is_notified"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	CategoryName  string    `json:"category_name"`
}

func (q *Queries) GetRecentForumPosts(ctx context.Context, arg GetRecentForumPostsParams) ([]*GetRecentForumPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetRecentForumPosts, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetRecentForumPostsRow{}
	for rows.Next() {
		var i GetRecentForumPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Title,
			&i.Author,
			&i.SourceTopicID,
			&i.SourceUrl,
			&i.Content,
			&i.ReplyCount,
			&i.ViewCount,
			&i.LastPostTime,
			&i.ContentHash,
			&i.HasImages,
			pq.Array(&i.ImageUrls),
			&i.IsNotified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUnnotifiedPosts = `-- name: GetUnnotifiedPosts :many
SELECT id, category_id, title, author, source_topic_id, source_url, content, reply_count, view_count, last_post_time, content_hash, has_images, image_urls, is_notified, created_at, updated_at FROM forum_topics
WHERE is_notified = false
ORDER BY created_at ASC
`

func (q *Queries) GetUnnotifiedPosts(ctx context.Context) ([]*ForumTopic, error) {
	rows, err := q.db.QueryContext(ctx, GetUnnotifiedPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ForumTopic{}
	for rows.Next() {
		var i ForumTopic
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Title,
			&i.Author,
			&i.SourceTopicID,
			&i.SourceUrl,
			&i.Content,
			&i.ReplyCount,
			&i.ViewCount,
			&i.LastPostTime,
			&i.ContentHash,
			&i.HasImages,
			pq.Array(&i.ImageUrls),
			&i.IsNotified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkPostAsNotified = `-- name: MarkPostAsNotified :exec
UPDATE forum_topics
SET is_notified = true, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkPostAsNotified(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, MarkPostAsNotified, id)
	return err
}
