// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Category struct {
	ID         int32     `json:"id"`
	Name       string    `json:"name"`
	Slug       string    `json:"slug"`
	SourceType string    `json:"source_type"`
	SourceUrl  string    `json:"source_url"`
	IsActive   bool      `json:"is_active"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type ForumTopic struct {
	ID            int32     `json:"id"`
	CategoryID    int32     `json:"category_id"`
	Title         string    `json:"title"`
	Author        string    `json:"author"`
	SourceTopicID string    `json:"source_topic_id"`
	SourceUrl     string    `json:"source_url"`
	Content       string    `json:"content"`
	ReplyCount    int32     `json:"reply_count"`
	ViewCount     int32     `json:"view_count"`
	LastPostTime  time.Time `json:"last_post_time"`
	ContentHash   string    `json:"content_hash"`
	HasImages     bool      `json:"has_images"`
	ImageUrls     []string  `json:"image_urls"`
	IsNotified    bool      `json:"is_notified"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Notification struct {
	ID                int32          `json:"id"`
	UserID            int32          `json:"user_id"`
	TopicID           int32          `json:"topic_id"`
	MessageText       string         `json:"message_text"`
	Status            string         `json:"status"`
	TelegramMessageID sql.NullInt32  `json:"telegram_message_id"`
	ErrorMessage      sql.NullString `json:"error_message"`
	RetryCount        int32          `json:"retry_count"`
	NextRetryAt       time.Time      `json:"next_retry_at"`
	SentAt            time.Time      `json:"sent_at"`
	CreatedAt         time.Time      `json:"created_at"`
}

type Subscription struct {
	ID         int32     `json:"id"`
	UserID     int32     `json:"user_id"`
	CategoryID int32     `json:"category_id"`
	IsActive   bool      `json:"is_active"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type User struct {
	ID           int32          `json:"id"`
	TelegramID   int64          `json:"telegram_id"`
	Username     sql.NullString `json:"username"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	LanguageCode sql.NullString `json:"language_code"`
	IsActive     bool           `json:"is_active"`
	IsAdmin      bool           `json:"is_admin"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	LastActivity time.Time      `json:"last_activity"`
}

type UserSetting struct {
	ID           int32     `json:"id"`
	UserID       int32     `json:"user_id"`
	SettingKey   string    `json:"setting_key"`
	SettingValue string    `json:"setting_value"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
