// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notifications.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const CountNotificationsByStatus = `-- name: CountNotificationsByStatus :one
SELECT COUNT(*) FROM notifications WHERE status = $1
`

func (q *Queries) CountNotificationsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountNotificationsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountUserNotifications = `-- name: CountUserNotifications :one
SELECT COUNT(*) FROM notifications WHERE user_id = $1
`

func (q *Queries) CountUserNotifications(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountUserNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    user_id, topic_id, message_text, status, retry_count
) VALUES (
    $1, $2, $3, 'pending', 0
) RETURNING id, user_id, topic_id, message_text, status, telegram_message_id, error_message, retry_count, next_retry_at, sent_at, created_at
`

type CreateNotificationParams struct {
	UserID      int32  `json:"user_id"`
	TopicID     int32  `json:"topic_id"`
	MessageText string `json:"message_text"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (*Notification, error) {
	row := q.db.QueryRowContext(ctx, CreateNotification, arg.UserID, arg.TopicID, arg.MessageText)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TopicID,
		&i.MessageText,
		&i.Status,
		&i.TelegramMessageID,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.NextRetryAt,
		&i.SentAt,
		&i.CreatedAt,
	)
	return &i, err
}

const DeleteOldNotifications = `-- name: DeleteOldNotifications :exec
DELETE FROM notifications
WHERE created_at < $1 AND status IN ('sent', 'failed')
`

func (q *Queries) DeleteOldNotifications(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, DeleteOldNotifications, createdAt)
	return err
}

const GetFailedNotifications = `-- name: GetFailedNotifications :many
SELECT id, user_id, topic_id, message_text, status, telegram_message_id, error_message, retry_count, next_retry_at, sent_at, created_at FROM notifications
WHERE status = 'failed' AND retry_count < $1
ORDER BY created_at ASC
`

func (q *Queries) GetFailedNotifications(ctx context.Context, retryCount int32) ([]*Notification, error) {
	rows, err := q.db.QueryContext(ctx, GetFailedNotifications, retryCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TopicID,
			&i.MessageText,
			&i.Status,
			&i.TelegramMessageID,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.NextRetryAt,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetNotificationStats = `-- name: GetNotificationStats :one
SELECT
    COUNT(*) as total,
    COUNT(*) FILTER (WHERE status = 'pending') as pending,
    COUNT(*) FILTER (WHERE status = 'sent') as sent,
    COUNT(*) FILTER (WHERE status = 'failed') as failed,
    COUNT(*) FILTER (WHERE status = 'rate_limited') as rate_limited
FROM notifications
`

type GetNotificationStatsRow struct {
	Total       int64 `json:"total"`
	Pending     int64 `json:"pending"`
	Sent        int64 `json:"sent"`
	Failed      int64 `json:"failed"`
	RateLimited int64 `json:"rate_limited"`
}

func (q *Queries) GetNotificationStats(ctx context.Context) (*GetNotificationStatsRow, error) {
	row := q.db.QueryRowContext(ctx, GetNotificationStats)
	var i GetNotificationStatsRow
	err := row.Scan(
		&i.Total,
		&i.Pending,
		&i.Sent,
		&i.Failed,
		&i.RateLimited,
	)
	return &i, err
}

const GetNotificationsByUser = `-- name: GetNotificationsByUser :many
SELECT n.id, n.user_id, n.topic_id, n.message_text, n.status, n.telegram_message_id, n.error_message, n.retry_count, n.next_retry_at, n.sent_at, n.created_at, ft.title as topic_title, ft.source_url as topic_url
FROM notifications n
JOIN forum_topics ft ON n.topic_id = ft.id
WHERE n.user_id = $1
ORDER BY n.created_at DESC
LIMIT $2 OFFSET $3
`

type GetNotificationsByUserParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetNotificationsByUserRow struct {
	ID                int32          `json:"id"`
	UserID            int32          `json:"user_id"`
	TopicID           int32          `json:"topic_id"`
	MessageText       string         `json:"message_text"`
	Status            string         `json:"status"`
	TelegramMessageID sql.NullInt32  `json:"telegram_message_id"`
	ErrorMessage      sql.NullString `json:"error_message"`
	RetryCount        int32          `json:"retry_count"`
	NextRetryAt       time.Time      `json:"next_retry_at"`
	SentAt            time.Time      `json:"sent_at"`
	CreatedAt         time.Time      `json:"created_at"`
	TopicTitle        string         `json:"topic_title"`
	TopicUrl          string         `json:"topic_url"`
}

func (q *Queries) GetNotificationsByUser(ctx context.Context, arg GetNotificationsByUserParams) ([]*GetNotificationsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, GetNotificationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetNotificationsByUserRow{}
	for rows.Next() {
		var i GetNotificationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TopicID,
			&i.MessageText,
			&i.Status,
			&i.TelegramMessageID,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.NextRetryAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.TopicTitle,
			&i.TopicUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPendingNotifications = `-- name: GetPendingNotifications :many
SELECT id, user_id, topic_id, message_text, status, telegram_message_id, error_message, retry_count, next_retry_at, sent_at, created_at FROM notifications
WHERE status = 'pending' OR (status = 'rate_limited' AND next_retry_at <= NOW())
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetPendingNotifications(ctx context.Context, limit int32) ([]*Notification, error) {
	rows, err := q.db.QueryContext(ctx, GetPendingNotifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TopicID,
			&i.MessageText,
			&i.Status,
			&i.TelegramMessageID,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.NextRetryAt,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateNotificationRetry = `-- name: UpdateNotificationRetry :exec
UPDATE notifications
SET status = $2, retry_count = retry_count + 1,
    next_retry_at = $3, error_message = $4
WHERE id = $1
`

type UpdateNotificationRetryParams struct {
	ID           int32          `json:"id"`
	Status       string         `json:"status"`
	NextRetryAt  time.Time      `json:"next_retry_at"`
	ErrorMessage sql.NullString `json:"error_message"`
}

func (q *Queries) UpdateNotificationRetry(ctx context.Context, arg UpdateNotificationRetryParams) error {
	_, err := q.db.ExecContext(ctx, UpdateNotificationRetry,
		arg.ID,
		arg.Status,
		arg.NextRetryAt,
		arg.ErrorMessage,
	)
	return err
}

const UpdateNotificationStatus = `-- name: UpdateNotificationStatus :exec
UPDATE notifications
SET status = $2, telegram_message_id = $3, sent_at = $4, error_message = $5
WHERE id = $1
`

type UpdateNotificationStatusParams struct {
	ID                int32          `json:"id"`
	Status            string         `json:"status"`
	TelegramMessageID sql.NullInt32  `json:"telegram_message_id"`
	SentAt            time.Time      `json:"sent_at"`
	ErrorMessage      sql.NullString `json:"error_message"`
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error {
	_, err := q.db.ExecContext(ctx, UpdateNotificationStatus,
		arg.ID,
		arg.Status,
		arg.TelegramMessageID,
		arg.SentAt,
		arg.ErrorMessage,
	)
	return err
}
