// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"time"
)

type Querier interface {
	CountActiveUsers(ctx context.Context) (int64, error)
	CountCategories(ctx context.Context) (int64, error)
	CountNotificationsByStatus(ctx context.Context, status string) (int64, error)
	CountPostsByCategory(ctx context.Context, categoryID int32) (int64, error)
	CountPostsLast24h(ctx context.Context) (int64, error)
	CountSubscriptions(ctx context.Context) (int64, error)
	CountTotalPosts(ctx context.Context) (int64, error)
	CountUserNotifications(ctx context.Context, userID int32) (int64, error)
	CountUserSubscriptions(ctx context.Context, userID int32) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (*Category, error)
	CreateForumPost(ctx context.Context, arg CreateForumPostParams) (*ForumTopic, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (*Notification, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (*Subscription, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeactivateUserSubscriptions(ctx context.Context, userID int32) error
	DeleteOldNotifications(ctx context.Context, createdAt time.Time) error
	DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error
	GetActiveCategories(ctx context.Context) ([]*Category, error)
	GetActiveSubscriptions(ctx context.Context) ([]*GetActiveSubscriptionsRow, error)
	GetActiveUsers(ctx context.Context) ([]*User, error)
	GetAdminUsers(ctx context.Context) ([]*User, error)
	GetAllUsers(ctx context.Context) ([]*User, error)
	GetCategoriesBySourceType(ctx context.Context, sourceType string) ([]*Category, error)
	GetCategoryByID(ctx context.Context, id int32) (*Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (*Category, error)
	GetFailedNotifications(ctx context.Context, retryCount int32) ([]*Notification, error)
	GetForumPostByContentHash(ctx context.Context, contentHash string) (*ForumTopic, error)
	GetForumPostBySourceID(ctx context.Context, arg GetForumPostBySourceIDParams) (*ForumTopic, error)
	GetForumPostByURL(ctx context.Context, sourceUrl string) (*ForumTopic, error)
	GetLastScrapingTime(ctx context.Context) (interface{}, error)
	GetNotificationStats(ctx context.Context) (*GetNotificationStatsRow, error)
	GetNotificationsByUser(ctx context.Context, arg GetNotificationsByUserParams) ([]*GetNotificationsByUserRow, error)
	GetPendingNotifications(ctx context.Context, limit int32) ([]*Notification, error)
	GetPostsByCategory(ctx context.Context, arg GetPostsByCategoryParams) ([]*ForumTopic, error)
	GetRecentForumPosts(ctx context.Context, arg GetRecentForumPostsParams) ([]*GetRecentForumPostsRow, error)
	GetRecentUsers(ctx context.Context, limit int32) ([]*User, error)
	GetSubscribersByCategory(ctx context.Context, categoryID int32) ([]*User, error)
	GetSubscriptionByUserAndCategory(ctx context.Context, arg GetSubscriptionByUserAndCategoryParams) (*Subscription, error)
	GetUnnotifiedPosts(ctx context.Context) ([]*ForumTopic, error)
	GetUserByID(ctx context.Context, id int32) (*User, error)
	GetUserByTelegramID(ctx context.Context, telegramID int64) (*User, error)
	GetUserSubscriptions(ctx context.Context, userID int32) ([]*GetUserSubscriptionsRow, error)
	MarkPostAsNotified(ctx context.Context, id int32) error
	SetUserActive(ctx context.Context, arg SetUserActiveParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (*Category, error)
	UpdateNotificationRetry(ctx context.Context, arg UpdateNotificationRetryParams) error
	UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error
	UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error)
	UpdateUserActivity(ctx context.Context, telegramID int64) error
}

var _ Querier = (*Queries)(nil)
