// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: subscriptions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const CountSubscriptions = `-- name: CountSubscriptions :one
SELECT COUNT(*) FROM subscriptions WHERE is_active = true
`

func (q *Queries) CountSubscriptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountSubscriptions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountUserSubscriptions = `-- name: CountUserSubscriptions :one
SELECT COUNT(*) FROM subscriptions WHERE user_id = $1 AND is_active = true
`

func (q *Queries) CountUserSubscriptions(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountUserSubscriptions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    user_id, category_id, is_active
) VALUES (
    $1, $2, $3
) ON CONFLICT (user_id, category_id)
DO UPDATE SET is_active = $3, updated_at = NOW()
RETURNING id, user_id, category_id, is_active, created_at, updated_at
`

type CreateSubscriptionParams struct {
	UserID     int32 `json:"user_id"`
	CategoryID int32 `json:"category_id"`
	IsActive   bool  `json:"is_active"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (*Subscription, error) {
	row := q.db.QueryRowContext(ctx, CreateSubscription, arg.UserID, arg.CategoryID, arg.IsActive)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const DeactivateUserSubscriptions = `-- name: DeactivateUserSubscriptions :exec
UPDATE subscriptions
SET is_active = false, updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) DeactivateUserSubscriptions(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, DeactivateUserSubscriptions, userID)
	return err
}

const DeleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions
WHERE user_id = $1 AND category_id = $2
`

type DeleteSubscriptionParams struct {
	UserID     int32 `json:"user_id"`
	CategoryID int32 `json:"category_id"`
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, DeleteSubscription, arg.UserID, arg.CategoryID)
	return err
}

const GetActiveSubscriptions = `-- name: GetActiveSubscriptions :many
SELECT s.id, s.user_id, s.category_id, s.is_active, s.created_at, s.updated_at, u.telegram_id, u.username, c.name as category_name
FROM subscriptions s
JOIN users u ON s.user_id = u.id
JOIN categories c ON s.category_id = c.id
WHERE s.is_active = true AND u.is_active = true
ORDER BY c.name, u.username
`

type GetActiveSubscriptionsRow struct {
	ID           int32          `json:"id"`
	UserID       int32          `json:"user_id"`
	CategoryID   int32          `json:"category_id"`
	IsActive     bool           `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	TelegramID   int64          `json:"telegram_id"`
	Username     sql.NullString `json:"username"`
	CategoryName string         `json:"category_name"`
}

func (q *Queries) GetActiveSubscriptions(ctx context.Context) ([]*GetActiveSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetActiveSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetActiveSubscriptionsRow{}
	for rows.Next() {
		var i GetActiveSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TelegramID,
			&i.Username,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetSubscribersByCategory = `-- name: GetSubscribersByCategory :many
SELECT u.id, u.telegram_id, u.username, u.first_name, u.last_name, u.language_code, u.is_active, u.is_admin, u.created_at, u.updated_at, u.last_activity FROM users u
JOIN subscriptions s ON u.id = s.user_id
WHERE s.category_id = $1 AND s.is_active = true AND u.is_active = true
`

func (q *Queries) GetSubscribersByCategory(ctx context.Context, categoryID int32) ([]*User, error) {
	rows, err := q.db.QueryContext(ctx, GetSubscribersByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TelegramID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.LanguageCode,
			&i.IsActive,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetSubscriptionByUserAndCategory = `-- name: GetSubscriptionByUserAndCategory :one
SELECT id, user_id, category_id, is_active, created_at, updated_at FROM subscriptions
WHERE user_id = $1 AND category_id = $2
`

type GetSubscriptionByUserAndCategoryParams struct {
	UserID     int32 `json:"user_id"`
	CategoryID int32 `json:"category_id"`
}

func (q *Queries) GetSubscriptionByUserAndCategory(ctx context.Context, arg GetSubscriptionByUserAndCategoryParams) (*Subscription, error) {
	row := q.db.QueryRowContext(ctx, GetSubscriptionByUserAndCategory, arg.UserID, arg.CategoryID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetUserSubscriptions = `-- name: GetUserSubscriptions :many
SELECT s.id, s.user_id, s.category_id, s.is_active, s.created_at, s.updated_at, c.name as category_name, c.slug as category_slug
FROM subscriptions s
JOIN categories c ON s.category_id = c.id
WHERE s.user_id = $1 AND s.is_active = true
ORDER BY c.name
`

type GetUserSubscriptionsRow struct {
	ID           int32     `json:"id"`
	UserID       int32     `json:"user_id"`
	CategoryID   int32     `json:"category_id"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	CategoryName string    `json:"category_name"`
	CategorySlug string    `json:"category_slug"`
}

func (q *Queries) GetUserSubscriptions(ctx context.Context, userID int32) ([]*GetUserSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetUserSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetUserSubscriptionsRow{}
	for rows.Next() {
		var i GetUserSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateSubscription = `-- name: UpdateSubscription :exec
UPDATE subscriptions
SET is_active = $2, updated_at = NOW()
WHERE user_id = $1 AND category_id = $3
`

type UpdateSubscriptionParams struct {
	UserID     int32 `json:"user_id"`
	IsActive   bool  `json:"is_active"`
	CategoryID int32 `json:"category_id"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, UpdateSubscription, arg.UserID, arg.IsActive, arg.CategoryID)
	return err
}
