// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const CountActiveUsers = `-- name: CountActiveUsers :one
SELECT COUNT(*) FROM users WHERE is_active = true
`

func (q *Queries) CountActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateUser = `-- name: CreateUser :one
INSERT INTO users (
    telegram_id, username, first_name, last_name, language_code, is_active, is_admin
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, telegram_id, username, first_name, last_name, language_code, is_active, is_admin, created_at, updated_at, last_activity
`

type CreateUserParams struct {
	TelegramID   int64          `json:"telegram_id"`
	Username     sql.NullString `json:"username"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	LanguageCode sql.NullString `json:"language_code"`
	IsActive     bool           `json:"is_active"`
	IsAdmin      bool           `json:"is_admin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*User, error) {
	row := q.db.QueryRowContext(ctx, CreateUser,
		arg.TelegramID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.LanguageCode,
		arg.IsActive,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.LanguageCode,
		&i.IsActive,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivity,
	)
	return &i, err
}

const GetActiveUsers = `-- name: GetActiveUsers :many
SELECT id, telegram_id, username, first_name, last_name, language_code, is_active, is_admin, created_at, updated_at, last_activity FROM users WHERE is_active = true ORDER BY created_at DESC
`

func (q *Queries) GetActiveUsers(ctx context.Context) ([]*User, error) {
	rows, err := q.db.QueryContext(ctx, GetActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TelegramID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.LanguageCode,
			&i.IsActive,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetAdminUsers = `-- name: GetAdminUsers :many
SELECT id, telegram_id, username, first_name, last_name, language_code, is_active, is_admin, created_at, updated_at, last_activity FROM users WHERE is_admin = true AND is_active = true
`

func (q *Queries) GetAdminUsers(ctx context.Context) ([]*User, error) {
	rows, err := q.db.QueryContext(ctx, GetAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TelegramID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.LanguageCode,
			&i.IsActive,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetAllUsers = `-- name: GetAllUsers :many
SELECT id, telegram_id, username, first_name, last_name, language_code, is_active, is_admin, created_at, updated_at, last_activity FROM users ORDER BY created_at DESC
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]*User, error) {
	rows, err := q.db.QueryContext(ctx, GetAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TelegramID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.LanguageCode,
			&i.IsActive,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRecentUsers = `-- name: GetRecentUsers :many
SELECT id, telegram_id, username, first_name, last_name, language_code, is_active, is_admin, created_at, updated_at, last_activity FROM users
WHERE is_active = true
ORDER BY last_activity DESC
LIMIT $1
`

func (q *Queries) GetRecentUsers(ctx context.Context, limit int32) ([]*User, error) {
	rows, err := q.db.QueryContext(ctx, GetRecentUsers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TelegramID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.LanguageCode,
			&i.IsActive,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserByID = `-- name: GetUserByID :one
SELECT id, telegram_id, username, first_name, last_name, language_code, is_active, is_admin, created_at, updated_at, last_activity FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (*User, error) {
	row := q.db.QueryRowContext(ctx, GetUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.LanguageCode,
		&i.IsActive,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivity,
	)
	return &i, err
}

const GetUserByTelegramID = `-- name: GetUserByTelegramID :one
SELECT id, telegram_id, username, first_name, last_name, language_code, is_active, is_admin, created_at, updated_at, last_activity FROM users WHERE telegram_id = $1
`

func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramID int64) (*User, error) {
	row := q.db.QueryRowContext(ctx, GetUserByTelegramID, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.LanguageCode,
		&i.IsActive,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivity,
	)
	return &i, err
}

const SetUserActive = `-- name: SetUserActive :exec
UPDATE users
SET is_active = $2, updated_at = NOW()
WHERE telegram_id = $1
`

type SetUserActiveParams struct {
	TelegramID int64 `json:"telegram_id"`
	IsActive   bool  `json:"is_active"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.ExecContext(ctx, SetUserActive, arg.TelegramID, arg.IsActive)
	return err
}

const UpdateUser = `-- name: UpdateUser :one
UPDATE users
SET username = $2, first_name = $3, last_name = $4, language_code = $5, updated_at = NOW()
WHERE telegram_id = $1
RETURNING id, telegram_id, username, first_name, last_name, language_code, is_active, is_admin, created_at, updated_at, last_activity
`

type UpdateUserParams struct {
	TelegramID   int64          `json:"telegram_id"`
	Username     sql.NullString `json:"username"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	LanguageCode sql.NullString `json:"language_code"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error) {
	row := q.db.QueryRowContext(ctx, UpdateUser,
		arg.TelegramID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.LanguageCode,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.LanguageCode,
		&i.IsActive,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivity,
	)
	return &i, err
}

const UpdateUserActivity = `-- name: UpdateUserActivity :exec
UPDATE users
SET last_activity = NOW(), updated_at = NOW()
WHERE telegram_id = $1
`

func (q *Queries) UpdateUserActivity(ctx context.Context, telegramID int64) error {
	_, err := q.db.ExecContext(ctx, UpdateUserActivity, telegramID)
	return err
}
